export const WEBSITE_GRAPH = 'WEBSITE_GRAPH';
export const NEW_USERS = 'NEW_USERS';
export const NEW_WEBSITE = 'NEW_WEBSITE';
export const FETCH_WEBSITES = 'FETCH_WEBSITES';
export const SINLGE_WEBSITE = 'SINLGE_WEBSITE';
